services:
  - type: web
    name: word-counter
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download nl_core_news_sm
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 